server:
  port: 5062

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/hackathon
    username: root
    password: test1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

jwt:
  secret: eW91ci1zdXBlci1zZWNyZXQta2V5LXNob3VsZC1iZS1sb25nLWVub3VnaA==
  access-token-expiry: 3600000       # 1시간 (1h)
  refresh-token-expiry: 604800000    # 7일 (7d)

